git:
  depth: 1
language: node_js
node_js:
- '4'
cache:
  directories:
  - node_modules
before_script:
# - npm install npm -g
# - npm install gulp-cli -g
- chmod +x ./deploy-website.sh
script: "./deploy-website.sh"
env:
  global:
notifications:
  slack:
    secure: WoDXcpxsMqXJJECRJiiLOCaVlXXonZWzAVVtPrvXsSd3Jk4wfwMI0uztpayIY2fXa/pyD/lC8lumAXxaYkaNStAqBfsYcVS6kbdyK5z9lingARu08Ozi/eSISDpnkj+H7HUqhDXDaEJ+fAlqFEmC13xhlB+sqFbHOJayHCDq+eAqyPFINxchrCSVlr9j6nlSfuRQAnRZdEzkEyMy7nmPzBC+0BBW75NAePl0iR8JaTlmpIM4sC17wY6FtWU06+SLAackoaiiujUaAVqRM+CgrB+RxgnZ8x97cZrohinB6spw8Up0UMz3OBd7JlsADpNK6FLDgPR7dXxEaOyWkbJL8nrU+DojHLHViym0R/kLWKhR4GWiHUlZ1PRLzc3mtqULF1QzL9pFExVj8/AB4KVdpIS7YuoofzmhZ2/GnECatlkllYUNML9WckFtxgjVfUIy7/KGQKlRz5O5fhmHqHl3RY91EUX8ZOVoqiLzW0ddUu3ALONGNhoz8UK1mH7CQAmoa2DRIRawzxzcf53uptHIq2qUZPPChSJtaQlTbWSmWM97W9v3QtqBHZ5UWefiR2I0TO8LLSoWCWQzGmWNr6EobN0udcdr2BD9tLOWZL0VvYWQPnkFMChyY6lyJnJjZvU+3pvT+LeqRukI7RlfFgRgJt+DuOAVs8gQeimjLO2d9mU=
